"""
Optimize aspect ratio of Advanced Single Aisle aircraft to minimize fuel burn.

connect to the aerodynamic polar database generated by FlightStream

"""
import numpy as np
import openmdao.api as om
import aviary.api as av
import pandas as pd

# Allow for user overrides here, add the FlightStream polar data
# Path to your aircraft definition file
aircraft_filename = r"C:\Users\AA201\Aviary\aviary\subsystems\aerodynamics\FlightStream_based\advanced_single_aisle_FLOPS.csv"
optimizer = 'SLSQP'
make_plots = True
max_iter = 100


# 你的 FS 极谱 npz 路径
fs_npz_path = r"C:\Users\AA201\Aviary\aviary\subsystems\aerodynamics\FlightStream_based\fs_polar_output\fs_asa_polar.npz"

def build_tabular_from_fs(fs_npz_path, alt_target_ft=35000.0, n_CL=25):
    """
    从 FlightStream 极谱 fs_asa_polar.npz 自动构造 Aviary Tabular Aero
    需要的 NamedValues: CD0_data 和 CDI_data。
    - CD0: altitude, mach -> zero_lift_drag_coefficient
    - CDI: mach, CL -> lift_dependent_drag_coefficient
    """

    fs_npz = np.load(fs_npz_path)

    # 读原始极谱
    alt_grid_m   = np.asarray(fs_npz["alt_grid"]).reshape(-1)      # (n_alt,)
    mach_grid    = np.asarray(fs_npz["mach_grid"]).reshape(-1)     # (n_mach,)
    alpha_grid   = np.asarray(fs_npz["alpha_grid"]).reshape(-1)    # (n_alpha,)
    CL_tab       = np.asarray(fs_npz["CL_tab"])
    CD_tab       = np.asarray(fs_npz["CD_tab"])

    # 单位转换：m -> ft
    alt_grid_ft = alt_grid_m / 0.3048

    n_alt   = alt_grid_ft.size
    n_mach  = mach_grid.size
    n_alpha = alpha_grid.size

    # 安全检查
    expected_shape = (n_alt, n_mach, n_alpha)
    if CL_tab.shape != expected_shape or CD_tab.shape != expected_shape:
        raise RuntimeError(
            f"FS 极谱维度不对: CL_tab.shape={CL_tab.shape}, "
            f"预期={expected_shape} (n_alt, n_mach, n_alpha)"
        )

    # ========== 1) 计算 CD0(alt, mach) ==========
    CD0_table = np.zeros((n_alt, n_mach))

    for i in range(n_alt):
        for j in range(n_mach):
            CL_line = CL_tab[i, j, :]
            CD_line = CD_tab[i, j, :]

            # CL 跨过 0 的情况：插值到 CL=0
            if (CL_line.min() <= 0.0) and (CL_line.max() >= 0.0):
                CD0_ij = np.interp(0.0, CL_line, CD_line)
            else:  # 不跨 0：取 |CL| 最小的点
                idx_min = np.argmin(np.abs(CL_line))
                CD0_ij = CD_line[idx_min]

            CD0_table[i, j] = CD0_ij

    # 把 (alt, mach) 网格展开成一维样本
    ALT_2D, MACH_2D = np.meshgrid(alt_grid_ft, mach_grid, indexing='ij')  # (n_alt, n_mach)
    alt_samples  = ALT_2D.ravel()           # (n_alt*n_mach,)
    mach_samples = MACH_2D.ravel()          # (n_alt*n_mach,)
    cd0_samples  = CD0_table.ravel()        # (n_alt*n_mach,)

    # ---- 生成 CD0_data ----
    CD0_data = av.NamedValues()
    CD0_data.set_val('altitude', alt_samples,  units='ft')
    CD0_data.set_val('mach',     mach_samples, units='unitless')
    CD0_data.set_val('zero_lift_drag_coefficient',
                     cd0_samples,              units='unitless')

    # ========== 2) 计算 CDI(mach, CL) ==========
    # 选一个代表高度（默认 35,000 ft）做升力相关阻力
    i_ref = int(np.argmin(np.abs(alt_grid_ft - alt_target_ft)))

    # 找所有 Mach 下共同的 CL 范围
    CL_min_list = []
    CL_max_list = []
    for j in range(n_mach):
        CL_line = CL_tab[i_ref, j, :]
        CL_min_list.append(CL_line.min())
        CL_max_list.append(CL_line.max())

    CL_min = max(CL_min_list)
    CL_max = min(CL_max_list)

    # 在公共范围内建一个统一的 CL 网格
    CL_grid = np.linspace(CL_min, CL_max, n_CL)

    # CDI_table: (n_mach, n_CL)
    CDI_table = np.zeros((n_mach, n_CL))

    for j in range(n_mach):
        CL_line = CL_tab[i_ref, j, :]
        CD_line = CD_tab[i_ref, j, :]

        # 对当前 Mach 下代表高度的 CD0
        if (CL_line.min() <= 0.0) and (CL_line.max() >= 0.0):
            CD0_ref = np.interp(0.0, CL_line, CD_line)
        else:
            idx_min = np.argmin(np.abs(CL_line))
            CD0_ref = CD_line[idx_min]

        # 升力相关阻力: CDi(CL) = CD(CL) - CD0_ref
        CDi_line = CD_line - CD0_ref

        # 插值到统一的 CL_grid
        CDI_table[j, :] = np.interp(CL_grid, CL_line, CDi_line)

    # 展开成一维样本 (mach, CL, CDi)
    MACH_2D, CL_2D = np.meshgrid(mach_grid, CL_grid, indexing='ij')   # (n_mach, n_CL)
    mach_cdi_samples = MACH_2D.ravel()         # (n_mach*n_CL,)
    CL_samples       = CL_2D.ravel()
    cdi_samples      = CDI_table.ravel()

    # ---- 生成 CDI_data ----
    CDI_data = av.NamedValues()
    CDI_data.set_val('mach', mach_cdi_samples, units='unitless')
    CDI_data.set_val('lift_coefficient', CL_samples, units='unitless')
    CDI_data.set_val('lift_dependent_drag_coefficient',
                     cdi_samples,       units='unitless')

    return CD0_data, CDI_data, cd0_samples, cdi_samples

# 调用一次，得到供后面 phase_info 使用的 NamedValues
CD0_data, CDI_data, cd0_samples, cdi_samples = build_tabular_from_fs(fs_npz_path)

# Define mission phases and their options
phase_info = {
    'pre_mission': {'include_takeoff': False, 'optimize_mass': True},
    'climb_1': {
        'subsystem_options': {'core_aerodynamics': {'method': 'tabular',
                                                    'CD0_data': CD0_data,
                                                    'CDI_data': CDI_data,
                                                    'structured': False,
                                                    'connect_training_data': True,}},
        'user_options': {
            'num_segments': 5,
            'order': 3,
            'mach_optimize': False,
            'mach_polynomial_order': 1,
            'mach_initial': (0.2, 'unitless'),
            'mach_final': (0.72, 'unitless'),
            'mach_bounds': ((0.18, 0.84), 'unitless'),
            'altitude_optimize': False,
            'altitude_polynomial_order': 1,
            'altitude_initial': (0.0, 'ft'),
            'altitude_final': (32500.0, 'ft'),
            'altitude_bounds': ((0.0, 33000.0), 'ft'),
            'throttle_enforcement': 'path_constraint',
            'time_initial_bounds': ((0.0, 0.0), 'min'),
            'time_duration_bounds': ((35.0, 105.0), 'min'),
        },
        'initial_guesses': {'time': ([0, 70], 'min')},
    },
    'cruise': {
        'subsystem_options': {'core_aerodynamics': {'method': 'tabular',
                                                    'CD0_data': CD0_data,
                                                    'CDI_data': CDI_data,
                                                    'structured': False,
                                                    'connect_training_data': True,}},
        'user_options': {
            'num_segments': 5,
            'order': 3,
            'mach_optimize': False,
            'mach_polynomial_order': 1,
            'mach_initial': (0.72, 'unitless'),
            'mach_final': (0.80, 'unitless'),
            'mach_bounds': ((0.7, 0.84), 'unitless'),
            'altitude_optimize': False,
            'altitude_polynomial_order': 1,
            'altitude_initial': (32500.0, 'ft'),
            'altitude_final': (36000.0, 'ft'),
            'altitude_bounds': ((32000.0, 36500.0), 'ft'),
            'throttle_enforcement': 'boundary_constraint',
            'time_initial_bounds': ((35.0, 105.0), 'min'),
            'time_duration_bounds': ((91.5, 274.5), 'min'),
        },
        'initial_guesses': {'time': ([70, 183], 'min')},
    },
    'descent_1': {
        'subsystem_options': {'core_aerodynamics': {'method': 'tabular',
                                                    'CD0_data': CD0_data,
                                                    'CDI_data': CDI_data,
                                                    'structured': False,
                                                    'connect_training_data': True,}},
        'user_options': {
            'num_segments': 5,
            'order': 3,
            'mach_optimize': False,
            'mach_polynomial_order': 1,
            'mach_initial': (0.80, 'unitless'),
            'mach_final': (0.21, 'unitless'),
            'mach_bounds': ((0.19, 0.84), 'unitless'),
            'altitude_optimize': False,
            'altitude_polynomial_order': 1,
            'altitude_initial': (36000.0, 'ft'),
            'altitude_final': (0.0, 'ft'),
            'altitude_bounds': ((0.0, 36500.0), 'ft'),
            'throttle_enforcement': 'path_constraint',
            'time_initial_bounds': ((126.5, 379.5), 'min'),
            'time_duration_bounds': ((25.0, 75.0), 'min'),
        },
        'initial_guesses': {'time': ([253, 50], 'min')},
    },
    'post_mission': {
        'include_landing': False,
        'constrain_range': True,
        'target_range': (1600, 'nmi'),
    },
}

# Load aircraft and options data from user
# Allow for user overrides here angain

prob = av.AviaryProblem()

prob.load_inputs(aircraft_filename, phase_info)

# Pass the polars to Aviary
#prob.aviary_inputs.set_val(av.Aircraft.Design.LIFT_POLAR, CL_tab, units='unitless')
#prob.aviary_inputs.set_val(av.Aircraft.Design.DRAG_POLAR, CD_tab, units='unitless')

#Check and preprocess inputs to register new data
prob.check_and_preprocess_inputs()

#Update the polars in the problem inputs
prob.aviary_inputs.set_val(
    av.Aircraft.Design.LIFT_INDEPENDENT_DRAG_POLAR,
    cd0_samples,
    units='unitless',
)

prob.aviary_inputs.set_val(
    av.Aircraft.Design.LIFT_DEPENDENT_DRAG_POLAR,
    cdi_samples,
    units='unitless',
)

prob.build_model()

prob.add_driver(optimizer, max_iter=max_iter)

# Design Variables
prob.add_design_variables()
# Aspect Ratio
prob.model.add_design_var(av.Aircraft.Wing.ASPECT_RATIO, lower=10.0, upper=20.0, ref=12.0)
# Wing Area
prob.model.add_design_var(av.Aircraft.Wing.AREA, lower=1000.0, upper=1500.0, ref=1220.0)
# Wing Sweep
prob.model.add_design_var(av.Aircraft.Wing.SWEEP, lower=0.0, upper=75.0, ref=20.0)
# Taper Ratio
prob.model.add_design_var(av.Aircraft.Wing.TAPER_RATIO, lower=0.1, upper=0.5, ref=0.26419)
# Dihedral Angle
prob.model.add_design_var(av.Aircraft.Wing.DIHEDRAL, lower=-5.0, upper=15.0, ref=6.0)
# Fuselage Length
prob.model.add_design_var(av.Aircraft.Fuselage.LENGTH, lower=100.0, upper=150.0, ref=125.0)
# Fuselage Compartment Length
prob.model.add_design_var(av.Aircraft.Fuselage.PASSENGER_COMPARTMENT_LENGTH, lower=80.0, upper=110.0, ref=97.5)
# Fuselage Max Height
prob.model.add_design_var(av.Aircraft.Fuselage.MAX_HEIGHT, lower=10.0, upper=15.0, ref=13.0)
# Fuselage Max Width
prob.model.add_design_var(av.Aircraft.Fuselage.MAX_WIDTH, lower=10.0, upper=15.0, ref=12.3)

prob.add_objective()
prob.setup()
prob.run_aviary_problem(make_plots=make_plots)

print("\n=== AVIARY GEOMETRY OPTIMIZATION COMPLETE ===\n")

# ------------------------------
# EXTRACT OUTPUTS FOR OAS
# ------------------------------
# Geometry Outputs
MTOW = prob.get_val(av.Mission.Design.GROSS_MASS)[0]
AR = prob.get_val(av.Aircraft.Wing.ASPECT_RATIO)
S = prob.get_val(av.Aircraft.Wing.AREA)
taper = prob.get_val(av.Aircraft.Wing.TAPER_RATIO)
sweep = prob.get_val(av.Aircraft.Wing.SWEEP)
fuselage_length = prob.get_val(av.Aircraft.Fuselage.LENGTH)
fuselage_width = prob.get_val(av.Aircraft.Fuselage.MAX_HEIGHT)
fuselage_height = prob.get_val(av.Aircraft.Fuselage.MAX_WIDTH)

# Derived geometric quantities needed by OAS
span = np.sqrt(AR * S)              # b = sqrt(AR * S)
c_avg = S / span                    # mean chord
mach = 0.78
alt_ft = 35000.0
alt_m = alt_ft * 0.3048
T = 218.8
a = np.sqrt(1.4 * 287.05 * T)
rho = 0.38  # kg/m^3 typical at 35k ft
n_load = 2.5

# ------------------------------
# PACK INTO DICTIONARY FOR OAS
# ------------------------------

oas_inputs = {
    "aspect_ratio": float(AR),
    "wing_area": float(S),
    "span": float(span),
    "mean_chord": float(c_avg),
    "taper_ratio": float(taper),
    "sweep_deg": float(sweep),
    "aircraft_mass": float(MTOW),
    "rho": rho,
    "mach": mach,
    "speed_of_sound": a,
    "load_factor": n_load,
}

outputs = {
    "aspect_ratio": float(AR),
    "wing_area [ft^2]": float(S),
    "span [ft]": float(span),
    "mean_chord [ft]": float(c_avg),
    "taper_ratio": float(taper),
    "sweep_deg [deg]": float(sweep),
    "MTOW [lbm]": float(MTOW),
    "fuselage_length [ft]": float(fuselage_length),
    "fuselage_width [ft]": float(fuselage_width),
    "fuselage_height [ft]": float(fuselage_height),
    "range [nmi]": prob.get_val(av.Mission.Summary.RANGE),
    "total_fuel_burn [lbm]": prob.get_val(av.Mission.Summary.FUEL_BURNED),
}

print("=== REQUIRED OAS STRUCTURAL INPUTS ===")
for k, v in outputs.items():
    print(f"{k:20s} : {v}")

print("\nSaved. You can now pass these into your OAS structural optimization script.\n")

# Emissions Estimation
#from emissions import compute_emissions
#emissions = compute_emissions(prob, make_plots=True)

# Compute Strucutre
#from structure import compute_structure
#structural_results = compute_structure(oas_inputs,plot_results=False)